/* 🤖 this file was generated by svg-to-ts*/

import { MyIcon } from '././my-icons.model';

export type IconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];

export * from '././portfolio-envelope.icon';
export * from '././portfolio-github.icon';
export * from '././portfolio-twitter.icon';
export * from '././my-icons.model';
